development:  
  adapter: postgresql
  encoding: utf8
  hostname: localhost
  port: 5432
  database: innovatron_development
  pool: 5
  username: innovatron
  password: innovatron

test:  
  adapter: postgresql
  encoding: utf8
  hostname: localhost
  port: 5432
  database: InnovaTron_test
  pool: 5
  username: innovatron
  password: innovatron